import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <div className="w-full flex flex-row items-center justify-end">
        <div className="flex flex-row items-center gap-4 w-[20%]">
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/dashboard/orders">Orders</Link>
          <Link href="/cart">Cart</Link>
        </div>
      </div>
      {children}
    </section>
  );
}
